[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:laravel-app]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /app/artisan serve --host=0.0.0.0 --port=8000
directory=/app
autostart=true
autorestart=true
user=root
stdout_logfile=/app/storage/logs/laravel.log
stderr_logfile=/app/storage/logs/laravel_error.log

[program:laravel-monitor]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /app/artisan so:monitor
directory=/app
autostart=true
autorestart=true
user=root
stdout_logfile=/app/storage/logs/monitor.log
stderr_logfile=/app/storage/logs/monitor_error.log
